/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted-surface)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
        "destructive-foreground": "var(--destructive-foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        "crowe-amber-bright": "#FFD231",
        "crowe-amber-core": "#F5A800",
        "crowe-amber-dark": "#D7761D",
        "crowe-indigo-bright": "#003F9F",
        "crowe-indigo-core": "#002E62",
        "crowe-indigo-dark": "#011E41",
        "crowe-tint-900": "#333333",
        "crowe-tint-700": "#4F4F4F",
        "crowe-tint-500": "#828282",
        "crowe-tint-300": "#BDBDBD",
        "crowe-tint-100": "#E0E0E0",
      },
    },
  },
  plugins: [],
};
